# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GFBG6mY0UUVusw45DpSWRUc78C2pYnd
"""

# snake_linkedlist.py

class Node:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.next = None


class LinkedList:
    def __init__(self):
        self.head = None

    def insert_at_beginning(self, x, y):
        new_node = Node(x, y)
        new_node.next = self.head
        self.head = new_node

    def delete_at_end(self):
        if self.head is None:
            return
        if self.head.next is None:
            self.head = None
            return
        prev = self.head
        temp = self.head.next
        while temp.next:
            prev = temp
            temp = temp.next
        prev.next = None

    def get_positions(self):
        positions = []
        temp = self.head
        while temp:
            positions.append((temp.x, temp.y))
            temp = temp.next
        return positions